@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 07 16:36:48 -0300 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim cic_int_comp_tb_behav -key {Behavioral:sim_1:Functional:cic_int_comp_tb} -tclbatch cic_int_comp_tb.tcl -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_param_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_comp_tb_behav.wcfg -log simulate.log"
call xsim  cic_int_comp_tb_behav -key {Behavioral:sim_1:Functional:cic_int_comp_tb} -tclbatch cic_int_comp_tb.tcl -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_param_tb_behav.wcfg -view D:/Documentos/Xilinx/FILTROS/ParamCIC/cic_int_comp_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
